name: Test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare the AVR Rust build environment
      run:
        docker build . --file Dockerfile.ci --tag avr-rust/avr-config.ci:$GITHUB_RUN_NUMBER

    - name: Compile the crate for AVR
      run:
        docker run avr-rust/avr-config.ci:$GITHUB_RUN_NUMBER build -Z build-std=core --target avr-atmega328p.json --release

    - name: Compile the crate and run tests for the host machine
      run:
        docker run avr-rust/avr-config.ci:$GITHUB_RUN_NUMBER test --all
